### ISSUE TITLE
Naming style

### ISSUE THREAD

**Issue by antagomir** [FelixErnst/MicrobiomeExperiment#12]
Underscoring has become more common lately, instead of CamelCase (vs. under_scoring). In my experience underscoring might work better. Both are allowed by Bioc. Something to consider.

**Comment by FelixErnst** [comment]
I would take a page from `SingleCellExperiment`/`scater`/`BioC` playbook.

- Function names are lowerCamelCase always containing a verb, if they do something, or describing the attribute to retrieve.
- Arguments use underscore notation
- Classes use plain CamelCase

Would that be aggreable?

/polls "Yes" "No"

**Comment by antagomir** [comment]
I suggest using undersocre notation also for functions. However, I accept and fully respect the decision of main package author.

**Comment by FelixErnst** [comment]
That is not something, I would like to dictate. I would rather get your opinion on this regarding the use in the referenced projects. I know this is contradictory to personal preferences (I would kick the underscore notation completely to the curb), but I would like to get a discussion on this

**Comment by FelixErnst** [comment]
[![](https://api.gh-polls.com/poll/01EN09P04WFV7JG6WSKHHGPFNP/Yes)](https://api.gh-polls.com/poll/01EN09P04WFV7JG6WSKHHGPFNP/Yes/vote)
[![](https://api.gh-polls.com/poll/01EN09P04WFV7JG6WSKHHGPFNP/No)](https://api.gh-polls.com/poll/01EN09P04WFV7JG6WSKHHGPFNP/No/vote)

**Comment by antagomir** [comment]
rOpenSci: "We strongly recommend snake_case over all other styles unless you are porting over a package that is already in wide use." [devguide 1.3.1](https://devguide.ropensci.org/building.html).

**Comment by FelixErnst** [comment]
You got a coin? 😄 

If I either of us says "whatever" this discussion will not end and come back up. For me constancy and acceptance is key.

Since we are more in the `SingleCellExperiment`/`scater`/`BioC` universe I consider it an argument to follow, what is happening there. The interfacing with those packages will be considerably and I something like `plot_stuff(reducedDim(altExp(me)))` works of course, but is unnecessary confusion. 

@fionarhuang @dombraccia @hcorrada @joey711 any comments?

**Comment by FelixErnst** [comment]
Or a vote in the poll above would be nice

**Comment by FelixErnst** [comment]
So I guess we go for the above mentioned scheme to keep it even across packages
