### ISSUE TITLE
Bioc checks: Dependencies and Remotes

### ISSUE THREAD

**Issue by antagomir** [FelixErnst/MicrobiomeExperiment#23]
* Checking for remote package usage...
    * ERROR: Package dependencies must be on CRAN or Bioconductor.
      Remove 'Remotes:' from DESCRIPTION

**Comment by FelixErnst** [comment]
Thats due to `SEtup` being a dependency for `mergeRows` function.

Whether `SEtup` will end up on Bioc depends a bit on how @LTLA and @Alanocallaghan think about it and whether splitting functions of from scater is the right way to go. Their are certain other options how this might work. 

I want to avoid a direct dependency of `ME` on `scater` since this will increase the dependency unnecessarily, at least in my mind.

**Comment by LTLA** [comment]
I assume you're referring to the `sumCountsAcrossFeatures` function, which has since moved to **scuttle**. This should reduce the dependency burden somewhat.

However, if your `ids` is always a factor, you could always just use `DelayedArray::rowsum`. The biggest reason for the existence of `sumCountsAcrossFeatures` is to handle the case where `ids` is a list with duplicated row indices across sets.

As for **SEtup**; we will need to consider its value after tightening the scope. There is not a lot of space to operate between generalist code that should go into the base SE package versus code that should go into domain-specific packages like **scuttle**.

**Comment by FelixErnst** [comment]
Thanks for the comment. Regarding the value of `SEtup` we are on the same page, that careful consideration is key.

The ideal situation from my point of view, would be that the implementation could be in a domain-agnostic package, so that we avoid reinventing the wheel. Sometimes I did that, just because I didn't know, the wheel existed in a domain-specific way and maybe this is something to avoid in the future. This can be the scope of `SEtup`: Avoiding reimplementation of essentially domain-agnostic operations in a domain-specific way.

For example the sum/merge function floating around are there to handle certain cases, which are all domain-agnostic, they just happen to be required in some domain earlier or more frequently and, therefore, are implemented in domain-specific packages sometimes with domain specific names. For now we have these functions working on the assay aka. matrix data:

- `rowsum`
- `DelayedArray::rowsum` (Wasn't familiar with the implementation in `DelayedArray`, but probably should have guessed)
- `sumCountsAcrossFeatures`

Within the `SE` world I think it might be a good idea to wrap all of those into one function, which then serves as a domain-agnostic goto. However, I am not sure on the specifics, since my experience with the `DelayedArray` backend are limited.

For working on a `SE` object directly, there is another set of functions:
- `aggregateAcrossFeatures`/`aggregateAcrossCells`
- `mergeRows`/`mergeCols`

The difference in these functions is that `aggregateAcross*` can handle overlapping factors for summing up, where `merge*` uses the `archetype` argument to select the `rowData/colData` to retain in the result. For each level in `ids`, a different `archetype` can be chosen, but usually the first one is used.

From these domain-agnostic operations domain-specific implementation can be derived to make it easy to work in the given domain. In the microbiome world `agglomerateByRank` is an example, which uses a taxonomic rank, to select which rows to sum up. Internally it uses `mergeRows`, which then uses `sumCountsAcrossFeatures` per assay.

This example might make sense, but it is the only example, I have come across.
- If you think the separation outlined above and boxing the operations into these two or three levels makes sense, we should have a case for `SEtup`.
- If it is the only example, that there is probably some overhead, which might be unnecessary. However, if the overhead is just initial, `SEtup` might be worth the time in the long run.

So this is a fine line to navigate. @LTLA How would you rate the chance of survival for `SEtup`? Apart from you, who do we need to involve and who would have an opinion, whether this is just my wishful thinking or actually makes sense?

**Comment by FelixErnst** [comment]
Closed since the `runCCA` and `sumAcross` issue is void, with the new release
